sudo: required
language: python
python:
- 3.5
services:
- docker
install:
- docker build --rm=true --file=Dockerfile -t lamp-virus .
script:
- docker run -it lamp-virus /usr/local/bin/collect_genomevirus.pl -p zika -q "txid64320[Organism:exp]"
  -a 2004 -b 2016
notifications:
  slack:
    secure: f7W7VZxL0+aLboj0RatC07I9s74+bETNiSIazxcI3IiPNZKSh90CfTE6ZgK+jbmGMAXOjaZmbqE81KgA2FLjcVj3xXgV8k4HOTgncZ+5v7k8/lSzd0Knm3Zg3djrvIReQPcHxO7ew7XM7mkWYmouJ61Cx5Ehc5O7gpvY/p39vWd/jJo9sGt0c6RlkAy2Zk8iLD1S5n84aEraSR7cuPzvXTvl0QoOultQyvl63Il4wLGWFYWHtjmgQH1xz6DWgR7P5ixtxl3qxoiFRnSOGhT5zl68OeiSDG/J7d/rk6TfU/wZ62D+lfkvchjoc8TFpisXuqBrO7fxK60RqufTW+42L7kDPyF8XD+hD2Ocqo2ZJf7YAhq601pY2iixTqdvg7rBxlCZR0UEcuL2OApXd1LMKF+J4IcZt3J7SqgsmDY8MrDltOWS2HqtMCLGj8mLm20JwHLUei1hrMFZ0cndINs51fqhi4yQwqHtYVWZ0GL7wBIB8tm+GAFNxXNWKn4w4i0Hewir+ST26QDK9cxVZRiIe8mJQ9X0SiA0eSxe9Cb2eGmwdfgCtb47JyqR4d3gSrF+S2k/MEwv4rH8yHBW+xyj2e0ocMSctcdNRvNGzK7RU5keFlLasYjPlTskOSKL4X84YToCjlZMkK1Z3VNG7xij+AATUJO744EZ/bQ8XMJrXqg=
