sudo: required
language: python
python:
- 3.5
services:
- docker
install:
- docker build --rm=true --file=Dockerfile -t lamp-virus .
script:
- docker run -it lamp-virus /usr/local/bin/collect_genomevirus.pl -p zika -q "txid64320[Organism:exp]"
  -a 2004 -b 2016
notifications:
  slack:
    secure: pt5iZYrmGoZEug/w3uNwS9O8SBeupP2a+2Q+f2v0ihRLl+v69cW8zx1vaFA/6583610QWO/5oiFhdnMK7/hvJpQp8tNpCulk0IRKURzt3tT2sBRfUElz4l3kjCuW0hZhT82pURZOfwuUl55ulstevd+jD6F4FlLS8eHDnIoAArCHflEIk9mPHcNe50uR2wRh9RWYCSDaGvUMFnq2isVYzTwkW51MxOtj4AJOGh6uEB9tG7SE9okZPpx4afZqYtG0GwDcq3Nm6l62iQgRTmAjd9f67uEQziQg4N4J8z0eFCXfftU5vplQ18U2EAE59CkCxWAfu/O/FHeec3lMzqKWSGzKcUHIT+CUP5VvDXT9BilLVD+UIi1GV9fOJY36lfA9dpJLunrcy5awADw9EbHGb7UXKGTcBeBNBvx7L5Wzcy+LBhibDxI5YOCxZkRSOSFI2ESau8WzC5ugAFNiQmAY5N70UZyOE8q8qo/HjgL5Tl4mfJmrPOMg3yI6wnny7Rjb+6AtTBAFXzqOiSlCubHXcCYbj1h9OyzVAQjdE3pwFAkggtRJDVIRVhzyt+OUobqcaNfOwtif2Pr/Azqi7nK9re4G4Td7OEWXoRgalURLVuQ6VwRWmCW1IiTYoWxL4+t6ToOuNzYMm2Z40hLia37TjLDjm4EdkDX6RvV05tjGF88=
